### PR TITLE
Editorial tweaks to the JOSS paper

### PR DESCRIPTION
**Pull request by leouieda**
Some very minor tweaks to the paper:

* Make the URLs in the table actual links
* Consistency in use of quotes around the package name
* Missing comma

openjournals/joss-reviews#2766

### CODE REVIEW

**Comment by leouieda** [comment]
Waiting on a preview of the PDF here: http://whedon.theoj.org/preview?id=5a684146d65de8c1ab4b34a3 Whedon seems to be taking a bit long.

**Comment by znicholls** [comment]
Looks great, let me know when you're done and I'll merge

**Comment by leouieda** [comment]
@znicholls I had some trouble with the rendering of the table so I simplified the Markdown syntax to fix them. The table looks slightly different in the rendered document but nothing major.

Here is a preview: [paper.pdf](https://github.com/openscm/openscm-twolayermodel/files/6638662/paper.pdf)

I'm done with this so feel free to make changes or merge.

**Comment by znicholls** [comment]
Awesome thanks!

**Comment by lewisjared** [comment]
Thanks @leouieda

**Pull request merged**
